### ISSUE TITLE
用最新版的拉取下来报错

### ISSUE THREAD

**Issue by muxang** [Next-DAO/atomicals-electrumx-proxy-docker#12]
INFO:Controller:shutdown complete
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/electrumx/electrumx_server", line 35, in main
    asyncio.run(controller.run())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/electrumx/electrumx/lib/server_base.py", line 129, in run
    await server_task
  File "/electrumx/electrumx/lib/server_base.py", line 102, in serve
    await self.serve(shutdown_event)
  File "/electrumx/electrumx/server/controller.py", line 137, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/electrumx/electrumx/lib/util.py", line 370, in join
    task.result()
  File "/electrumx/electrumx/server/block_processor.py", line 3468, in fetch_and_process_blocks
    await self._first_open_dbs()
  File "/electrumx/electrumx/server/block_processor.py", line 3447, in _first_open_dbs
    await self.db.open_for_sync()
  File "/electrumx/electrumx/server/db.py", line 360, in open_for_sync
    await self._open_dbs(True, False)
  File "/electrumx/electrumx/server/db.py", line 334, in _open_dbs
    self.read_utxo_state()
  File "/electrumx/electrumx/server/db.py", line 971, in read_utxo_state
    self.db_atomical_count = state['atomical_count']
KeyError: 'atomical_count'

**Comment by lucky2077** [comment]
看下 #10
