### ISSUE TITLE
atomicals-electrumx container exit with error

### ISSUE THREAD

**Issue by wqwljz** [Next-DAO/atomicals-electrumx-proxy-docker#15]
2023-11-30 22:31:33 INFO:DB:opened UTXO DB (for sync: True)
2023-11-30 22:31:33 INFO:Controller:shutting down
2023-11-30 22:31:33 INFO:Controller:shutdown complete
2023-11-30 22:31:33 ERROR:electrumx:ElectrumX server terminated abnormally
2023-11-30 22:31:33 Traceback (most recent call last):
2023-11-30 22:31:33   File "/electrumx/electrumx_server", line 35, in main
2023-11-30 22:31:33     asyncio.run(controller.run())
2023-11-30 22:31:33   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
2023-11-30 22:31:33     return loop.run_until_complete(main)
2023-11-30 22:31:33   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2023-11-30 22:31:33   File "/electrumx/electrumx/lib/server_base.py", line 129, in run
2023-11-30 22:31:33     await server_task
2023-11-30 22:31:33   File "/electrumx/electrumx/lib/server_base.py", line 102, in serve
2023-11-30 22:31:33     await self.serve(shutdown_event)
2023-11-30 22:31:33   File "/electrumx/electrumx/server/controller.py", line 137, in serve
2023-11-30 22:31:33     await group.spawn(wait_for_catchup())
2023-11-30 22:31:33   File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 297, in __aexit__
2023-11-30 22:31:33     await self.join()
2023-11-30 22:31:33   File "/electrumx/electrumx/lib/util.py", line 370, in join
2023-11-30 22:31:33     task.result()
2023-11-30 22:31:33   File "/electrumx/electrumx/server/block_processor.py", line 3497, in fetch_and_process_blocks
2023-11-30 22:31:33     await self._first_open_dbs()
2023-11-30 22:31:33   File "/electrumx/electrumx/server/block_processor.py", line 3476, in _first_open_dbs
2023-11-30 22:31:33     await self.db.open_for_sync()
2023-11-30 22:31:33   File "/electrumx/electrumx/server/db.py", line 360, in open_for_sync
2023-11-30 22:31:33     await self._open_dbs(True, False)
2023-11-30 22:31:33   File "/electrumx/electrumx/server/db.py", line 334, in _open_dbs
2023-11-30 22:31:33     self.read_utxo_state()
2023-11-30 22:31:33   File "/electrumx/electrumx/server/db.py", line 971, in read_utxo_state
2023-11-30 22:31:33     self.db_atomical_count = state['atomical_count']
2023-11-30 22:31:33 KeyError: 'atomical_count'

**Comment by wqwljz** [comment]
1. remove the data volume
2. restart the container
3. everything looks normal
