### ISSUE TITLE
electrumx-1 容器 50001端口没有启动。docker状态unhealthy

### ISSUE THREAD

**Issue by GeekXtop** [Next-DAO/atomicals-electrumx-proxy-docker#2]
```
2023-11-18 14:32:28 INFO:BlockProcessor:our height: 817,284 daemon: 817,284 UTXOs 2MB hist 1MB
2023-11-18 14:32:28 INFO:BlockProcessor:processed 1 block size 1.70 MB in 14.4s
2023-11-18 14:32:28 INFO:BlockProcessor:caught up to height 817284
2023-11-18 14:32:28 INFO:DB:flushed filesystem data in 0.00s
2023-11-18 14:32:28 INFO:History:flushed history in 0.0s for 8,918 addrs
2023-11-18 14:32:28 INFO:DB:flushed 1 blocks with 4,592 txs, 9,547 UTXO adds, 0 Atomical txs, 3 Atomical UTXO adds, 4,106 spends in 0.0s, committing...
2023-11-18 14:32:28 INFO:DB:flush #2,230 took 0.0s.  Height 817,284 txs: 921,390,859 (+4,592) Atomical txs: 85,197 (+0)
2023-11-18 14:32:28 INFO:DB:tx/sec since genesis: 1,455, since last flush: 307
2023-11-18 14:32:28 INFO:DB:sync time: 7d 07h 53m  ETA: 00s
2023-11-18 14:32:28 INFO:DB:closing DBs to re-open for serving
2023-11-18 14:32:28 INFO:DB:opened UTXO DB (for sync: False)
2023-11-18 14:32:28 INFO:DB:UTXO DB version: 8
2023-11-18 14:32:28 INFO:DB:coin: Bitcoin
2023-11-18 14:32:28 INFO:DB:network: mainnet
2023-11-18 14:32:28 INFO:DB:height: 817,284
2023-11-18 14:32:28 INFO:DB:tip: 0000000000000000000197766e3f7e8a196f98e799ff59220d55f36e5f4fe2d8
2023-11-18 14:32:28 INFO:DB:tx count: 921,390,859
2023-11-18 14:32:28 INFO:DB:atomical count: 85,197
2023-11-18 14:32:29 INFO:History:history DB version: 1
2023-11-18 14:32:29 INFO:History:flush count: 2,230
2023-11-18 14:32:29 INFO:DB:deleted 1 stale undo entries
2023-11-18 14:32:29 INFO:DB:deleted 1 stale atomicals undo entries
2023-11-18 14:32:29 INFO:DB:populating header merkle cache...
2023-11-18 14:32:29 INFO:MemPool:beginning processing of daemon mempool.  This can take some time...
2023-11-18 14:32:31 INFO:DB:header merkle cache populated in 1.9s
2023-11-18 14:32:31 Atomicals op script found: 03646d74
2023-11-18 14:32:31 Atomicals envelope and operation found: dmt
2023-11-18 14:32:31 Atomicals envelope payload: a16461726773a46474696d651a6554886b656e6f6e63651a006d198368626974776f726b6364616261666b6d696e745f7469636b657265626974766d
2023-11-18 14:32:31 INFO:MemPool:Found potential Atomicals operation in mempool transaction 4c80c67c5c7e58e34c139e924c86737a5c3f1612c6a3939efe0c3a1b6456a6ed, op=dmt
```

```
2023-11-18 14:32:34 Atomicals op script found: 03646d74
2023-11-18 14:32:34 Atomicals envelope and operation found: dmt
2023-11-18 14:32:34 Atomicals envelope payload: b900016461726773b900046b6d696e745f7469636b657265626974766d68626974776f726b636461626166656e6f6e63656839343536333038376474696d651a6554a5d3
2023-11-18 14:32:34 INFO:MemPool:Found potential Atomicals operation in mempool transaction 99d9648f396b1cae62114572403142e69bd9dd724d60e1e43a13b01696b19929, op=dmt
2023-11-18 14:32:34 Atomicals op script found: 036e6674
2023-11-18 14:32:34 Atomicals envelope and operation found: nft
2023-11-18 14:32:34 Atomicals envelope payload: b900016461726773b900046d726571756573745f7265616c6d636a7a3768626974776f726b636464366630656e6f6e63656834323839343830386474696d651a6549d110
2023-11-18 14:32:34 INFO:MemPool:Found potential Atomicals operation in mempool transaction 731bd0b1f7cf194a1441c6d38ab15f36dc3f5402c2c584ea003c8fc88fca0624, op=nft
2023-11-18 14:32:34 INFO:MemPool:Potential Atomicals mint NFT in mempool transaction 731bd0b1f7cf194a1441c6d38ab15f36dc3f5402c2c584ea003c8fc88fca0624, atomicalId=d6f0db12ec9180cc6539bc644b6ca3c91b3ef8e389f61d6c33a6e1d71758434ci0
2023-11-18 14:32:34 Atomicals op script found: 03646d74
2023-11-18 14:32:34 Atomicals envelope and operation found: dmt
2023-11-18 14:32:34 Atomicals envelope payload: a16461726773a468626974776f726b6364616261666b6d696e745f7469636b657265626974766d656e6f6e63651a00582eaf6474696d651a6554b90d
2023-11-18 14:32:34 INFO:MemPool:Found potential Atomicals operation in mempool transaction 05c7643c915f58648dfface272aba1e316507cdfc5a74ea4969ec1a5e97b359e, op=dmt
2023-11-18 14:34:56 INFO:Prefetcher:new block height 817,285 hash 000000000000000000040a33c42bdf725fe9c9f56c1d4e498fcd4eb491555f29
2023-11-18 14:36:56 INFO:Prefetcher:new block height 817,286 hash 000000000000000000031ab93d65ed9d0305d1ca536907f72e4f80ac467f3395
2023-11-18 14:40:52 INFO:Prefetcher:new block height 817,287 hash 00000000000000000001436926e0204ed7cefcd9257f71a2c457fb7d2cb6803f
```
看上面日志应该是已经追上最新块了吧。大佬麻烦看一下这样的日志是正常的吗，50001端口没有启动，健康检查过不去。

**Comment by lucky2077** [comment]
正常，当出现 `2023-11-18 14:32:28 INFO:DB:closing DBs to re-open for serving` 这个log的时候，应该很快就能 healthy 了

**Comment by GeekXtop** [comment]
> 正常，当出现 `2023-11-18 14:32:28 INFO:DB:closing DBs to re-open for serving` 这个log的时候，应该很快就能 healthy 了

还有个问题。经过多次实验。发现在Win11版本docker环境中，electrumx-1 跑着跑着就会卡死，退也退不了，这种情况只能重启docker，感觉还是有问题存在，会影响数据完整性吗？

我下载了那个76G的节点包解压放进去的

**Comment by lucky2077** [comment]
> > 正常，当出现 `2023-11-18 14:32:28 INFO:DB:closing DBs to re-open for serving` 这个log的时候，应该很快就能 healthy 了
> 
> 还有个问题。经过多次实验。发现在Win11版本docker环境中，electrumx-1 跑着跑着就会卡死，退也退不了，这种情况只能重启docker，感觉还是有问题存在，会影响数据完整性吗？
> 
> 我下载了那个76G的节点包解压放进去的

观察下你电脑的资源占用情况，刚刚一个朋友也是同样情况，一直不ready，然后发现内存占80%了，重启电脑，只开全节点和docker，很快就同步好了

**Comment by Alarical** [comment]
还是报错ERROR:Daemon:connection problem - check your daemon is running.  Retrying occasionally... 请问应该怎么解决？

**Comment by lmxpz169** [comment]
一样，请问解决了没有

**Comment by derekchan10** [comment]
@Alarical 这是你的BTC全节点的问题，看看是不是账号密码问题，或者你的全节点还没有同步好块

**Comment by Alarical** [comment]
> @Alarical 这是你的BTC全节点的问题，看看是不是账号密码问题，或者你的全节点还没有同步好块

应该不是，报这个错的时候，没办法同步节点，要在env文件改
DAEMON_URL=nextdao:nextdao@host.docker.internal:8332
，把自己的ip换成host.docker.internal就可以同步了

**Comment by Alarical** [comment]
> 一样，请问解决了没有

改这个DAEMON_URL=nextdao:[nextdao@host.docker.internal](mailto:nextdao@host.docker.internal):8332

**Comment by lmxpz169** [comment]
> 正常，当出现 `2023-11-18 14:32:28 INFO:DB:closing DBs to re-open for serving` 这个log的时候，应该很快就能 healthy 了

2023-11-18 21:56:38 atomicals-electrumx-docker-proxy-1      | GET / 304 2.683 ms - -
2023-11-18 21:56:59 atomicals-electrumx-docker-electrumx-1  | INFO:DB:flush #2,229 took 0.1s.  Height 817,314 txs: 921,531,684 (+3,293) Atomical txs: 85,198 (+0)
2023-11-18 21:56:59 atomicals-electrumx-docker-electrumx-1  | INFO:BlockProcessor:processed 1 block size 1.50 MB in 749.5s
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      | connectClient:exception Error: connect ECONNREFUSED 172.18.0.2:50001
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |   errno: -111,
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |   code: 'ECONNREFUSED',
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |   syscall: 'connect',
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |   address: '172.18.0.2',
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |   port: 50001
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      | }
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      | health_error 172.18.0.1 TypeError: Cannot read properties of null (reading 'serverDonation_address')
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |     at /app/src/api/proxy.ts:11:27
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      | GET /proxy/health 500 18.709 ms - 110
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      | Presisted Connection to ElectrumX(electrumx:50001) Server Closed.
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      | connectClient:exception Error: connect ECONNREFUSED 172.18.0.2:50001
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |   errno: -111,
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |   code: 'ECONNREFUSED',
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |   syscall: 'connect',
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |   address: '172.18.0.2',
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |   port: 50001
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      | }
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      | health_error 172.18.0.1 TypeError: Cannot read properties of null (reading 'serverDonation_address')
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |     at /app/src/api/proxy.ts:11:27
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      | GET /proxy/health 500 1.826 ms - 110
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      | Presisted Connection to ElectrumX(electrumx:50001) Server Closed.
2023-11-18 21:57:07 atomicals-electrumx-docker-proxy-1      | GET /favicon.ico 404 0.670 ms - 38


--------------
2023-11-18 14:32:28 INFO:DB:closing DBs to re-open for serving

这个我已经出现了，但还是出现以上报错，知道是什么原因吗

**Comment by lmxpz169** [comment]
ok 成功了， 感谢 回复。 还是得自己多研究下

**Comment by banglib** [comment]
使用/proxy/health 查询，返回
{"success":false,"health":false,"message":"Cannot read properties of null (reading 'serverDonation_address')"}
这是什么原因

**Comment by GeekXtop** [comment]
> 使用/proxy/health 查询，返回 {"success":false,"health":false,"message":"Cannot read properties of null (reading 'serverDonation_address')"} 这是什么原因

同样报这个错

**Comment by hhfcvmars** [comment]
> > 一样，请问解决了没有
> 
> 改这个DAEMON_URL=nextdao:[nextdao@host.docker.internal](mailto:nextdao@host.docker.internal):8332

是修改这个位置吗？
![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/62316749/d8f47f22-eb89-4e30-b688-a4ee4365c1e6)

我这修改了运行还是这个问题
![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/62316749/3a26f80a-b4ce-4d32-8124-ef8167030c11)

**Comment by hhfcvmars** [comment]
> > 一样，请问解决了没有
> 
> 改这个DAEMON_URL=nextdao:[nextdao@host.docker.internal](mailto:nextdao@host.docker.internal):8332

我这修改完，后面还是提示错误。该怎么操作
![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/62316749/cc527b23-e2b4-489e-bd77-bc260511ddd7)

![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/62316749/65df102f-f03e-46aa-8c55-a7c705aa3562)

**Comment by GeekXtop** [comment]
> > > 正常，当出现 `2023-11-18 14:32:28 INFO:DB:closing DBs to re-open for serving` 这个log的时候，应该很快就能 healthy 了
> > 
> > 
> > 还有个问题。经过多次实验。发现在Win11版本docker环境中，electrumx-1 跑着跑着就会卡死，退也退不了，这种情况只能重启docker，感觉还是有问题存在，会影响数据完整性吗？
> > 我下载了那个76G的节点包解压放进去的
> 
> 观察下你电脑的资源占用情况，刚刚一个朋友也是同样情况，一直不ready，然后发现内存占80%了，重启电脑，只开全节点和docker，很快就同步好了

老哥还是不行。docker停止不掉发现是卡这里
```
INFO:Prefetcher:cancelled; prefetcher stopping 
2023-11-19 16:26:15 INFO:BlockProcessor:flushing to DB for a clean shutdown...
```
![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/103322869/9bd8040f-5661-44de-a3d8-31943175bcb7)
![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/103322869/26e2ad0d-d6a2-40ba-9884-87bb79290e23)

**Comment by lesonmeta** [comment]
请问一下，为什么它没在更新节点，一直提示扫描历史数据。

**Comment by lesonmeta** [comment]
atomicals-electrumx-proxy-docker-main-electrumx-1  | INFO:BlockProcessor:advance_txs: create_or_delete_decentralized_mint_output:atomical_id_of_distmint - atomical_id=ad295fd6291cbb7b1f5b51b0c3fd862ee13f1ed1b9a0661917e6e8891f41967200000000, tx_hash=e36a7e732f35e0598bcce786ef066b0232e74134b789c305b316acae354b9d26
2023-11-21 03:29:05 atomicals-electrumx-proxy-docker-main-electrumx-1  | INFO:BlockProcessor:advance_txs: has_at_least_one_valid_atomicals_operation tx_hash=e36a7e732f35e0598bcce786ef066b0232e74134b789c305b316acae354b9d26   
为什么这里我不显示最新的区块数，而是显示advance？？？

**Comment by PingMaoer** [comment]
> ok 成功了， 感谢 回复。 还是得自己多研究下

请问，怎么解决的，老哥，我也卡在这一步了
